 # Calcul scientifique -- TP4 -- numpy

**Nom :** Diamoutene   
**Prénom:** zana

Ce TP reprend la fin du TP3 mais propose une suite (qui n'est pas une option!). Comme au TP3, il n'y a pas de boucles à écrire.

**Attention: exercice noté à la fin du TP5 (sur sympy et numpy, contenus des TP 1,2,3 et 4).**


Pour commencer, on importe la librairie  `numpy`

In [1]:
import numpy as np

### 1) Utilisation des index 

Creer un tableau nommé tab à une dimension de taille 19 avec des valeurs aléatoires puis l'afficher.
Ensuite , afficher les valeurs  dont les **indices** sont pairs  (attention, les indices pas les valeurs). L'instruction doit être valable pour n'importe quel tableau à 1 dimension, quel que soit le nombre de valeurs.

Pour comparer les méthodes, afficher les valeurs paires du tableau

In [1]:
# A compléter ...
import numpy as np
tab=np.random.randint(1,9,19)
print(tab)
pairs=tab[::2]
print(pairs)
inpairs=tab[1::2]
pairss= tab%2==0
print(pairss)


[4 6 6 8 4 3 1 2 7 6 2 8 2 6 8 1 4 4 4]
[4 6 4 1 7 2 2 8 4 4]
[ True  True  True  True  True False False  True False  True  True  True
  True  True  True False  True  True  True]


Afficher la somme des valeurs de tab dont les **indices** sont pairs puis la somme des éléments qui sont à des places multiples de 3 plus 1 (index: 1, 4, 7 etc...)

In [2]:
# A compléter ...
s1 = np.sum(tab[::2])
print('val indices pairs :',s1)
s2=np.sum(tab[::3])
print('val indices 1,4,7 etc :',s2)

val indices pairs : 42
val indices 1,4,7 etc : 26


### 2) Modifications dans un tableau à 2D
Créer un tableau `a` de taille 8x8 (8 lignes et 8 colonnes) rempli de valeurs aléatoires entières de 1 à 9 inclus. 

**Pour toutes les questions suivantes, nous travaillerons avec un tableau de taille 8x8  mais vos instructions devraient fonctionner pour un tableau de taille quelconque**

On fera un nouveau tableau par question pour mieux observer les résultats produits.



Au moyen du sélecteur approprié, remplacer toutes les valeurs du tableau par la valeur 0. Attention le nombre de lignes / colonnes doit être conservé. Afficher le résultat.
On doit remplacer les valeurs, pas créer un nouveau tableau.


In [3]:
# A compléter ...
a=np.random.randint(1,10,(8,8))

print(a)


# A compléter ...
a[:,:]=0
print("\nrésultat après modifications\n",a)

[[7 4 2 4 7 3 9 8]
 [2 2 5 7 9 4 1 3]
 [4 8 5 4 6 7 3 5]
 [3 4 1 4 2 9 3 3]
 [8 6 4 5 6 7 1 2]
 [3 9 5 7 3 8 8 3]
 [4 9 8 8 7 4 2 1]
 [6 9 2 9 2 9 6 1]]

résultat après modifications
 [[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


Créer un tableau `a` de taille  8x8 (8 lignes et 8 colonnes) rempli de valeurs aléatoires entières de 1 à 9 inclus,  puis mettre la première ligne du tableau à 0. 


In [4]:
# A compléter ...
a=np.random.randint(1,10,size=(8,8))
print(a)
a[0, :] = 0
print(a)


[[2 5 7 4 5 3 1 8]
 [3 7 2 2 3 3 6 4]
 [1 7 2 4 6 1 6 7]
 [1 2 6 7 3 3 3 4]
 [7 2 2 4 6 3 5 7]
 [1 9 8 6 7 1 4 2]
 [1 4 8 7 8 6 4 5]
 [8 8 3 4 8 5 2 5]]
[[0 0 0 0 0 0 0 0]
 [3 7 2 2 3 3 6 4]
 [1 7 2 4 6 1 6 7]
 [1 2 6 7 3 3 3 4]
 [7 2 2 4 6 3 5 7]
 [1 9 8 6 7 1 4 2]
 [1 4 8 7 8 6 4 5]
 [8 8 3 4 8 5 2 5]]


Créer un tableau `a` de taille  8x8 (8 lignes et 8 colonnes) rempli de valeurs aléatoires entières de 1 à 9 inclus puis mettre la colonne numéro 2 du tableau à 0. 


In [5]:
# A compléter ...
a=np.random.randint(1,10,size=(8,8))
print(a)
a[:,2]=0
print(a)

[[6 3 5 6 3 2 6 6]
 [1 4 6 1 1 5 6 6]
 [1 9 9 6 3 6 4 9]
 [6 2 3 4 2 8 4 5]
 [2 1 2 4 9 2 8 3]
 [2 8 3 1 9 4 7 6]
 [7 1 7 6 2 7 8 3]
 [3 1 1 9 1 9 4 7]]
[[6 3 0 6 3 2 6 6]
 [1 4 0 1 1 5 6 6]
 [1 9 0 6 3 6 4 9]
 [6 2 0 4 2 8 4 5]
 [2 1 0 4 9 2 8 3]
 [2 8 0 1 9 4 7 6]
 [7 1 0 6 2 7 8 3]
 [3 1 0 9 1 9 4 7]]


Créer un tableau `a` de taille  8x8 (8 lignes et 8 colonnes) rempli de valeurs aléatoires entières de 1 à 9 inclus,  puis mettre la première et la dernière colonne à 0 (en une seule instruction)

In [6]:
# A compléter ...
a=np.random.randint(1,10,size=(8,8))
print(a)
a[:,[0,7]]=0
print(a)

[[5 9 2 1 7 3 8 4]
 [5 4 5 8 7 9 9 3]
 [2 6 7 3 3 1 6 8]
 [6 3 9 1 3 5 4 2]
 [2 5 4 2 3 9 3 2]
 [7 9 6 3 3 6 5 1]
 [2 1 1 3 8 8 9 6]
 [9 3 1 8 5 6 5 9]]
[[0 9 2 1 7 3 8 0]
 [0 4 5 8 7 9 9 0]
 [0 6 7 3 3 1 6 0]
 [0 3 9 1 3 5 4 0]
 [0 5 4 2 3 9 3 0]
 [0 9 6 3 3 6 5 0]
 [0 1 1 3 8 8 9 0]
 [0 3 1 8 5 6 5 0]]


Créer un tableau `a`de taille  8x8 (8 lignes et 8 colonnes) rempli de valeurs aléatoires entières de 1 à 9 inclus puis mettre les 9 cases de la partie supérieure gauche du tableau à 0 en une seule instruction. 


In [7]:

a=np.random.randint(1,10,size=(8,8))
print(a)
a[:4,:4]=0
print(a)

[[2 2 8 2 4 5 6 8]
 [3 4 1 2 7 6 7 6]
 [4 6 9 2 8 2 6 2]
 [5 6 3 4 3 8 8 4]
 [9 3 3 8 4 7 3 3]
 [5 2 8 9 7 7 7 8]
 [6 5 1 2 1 9 3 4]
 [3 3 7 9 6 9 4 9]]
[[0 0 0 0 4 5 6 8]
 [0 0 0 0 7 6 7 6]
 [0 0 0 0 8 2 6 2]
 [0 0 0 0 3 8 8 4]
 [9 3 3 8 4 7 3 3]
 [5 2 8 9 7 7 7 8]
 [6 5 1 2 1 9 3 4]
 [3 3 7 9 6 9 4 9]]


Créer un tableau `a` de taille  8x8 (8 lignes et 8 colonnes) rempli de valeurs aléatoires entières de 1 à 9 inclus puis mettre  les cases qui sont sur des lignes **et** des colonnes paires à 0.

In [8]:
# A compléter ...
a=np.random.randint(1,10,size=(8,8))
print(a)
a[::2,::2]=0
print(a)

[[8 4 3 6 2 5 2 5]
 [4 1 4 9 2 9 5 9]
 [7 3 7 4 6 2 7 2]
 [4 5 1 4 2 3 1 5]
 [5 8 9 5 6 8 5 9]
 [8 6 1 5 7 8 8 4]
 [5 4 5 5 3 1 6 2]
 [5 5 5 4 5 7 2 2]]
[[0 4 0 6 0 5 0 5]
 [4 1 4 9 2 9 5 9]
 [0 3 0 4 0 2 0 2]
 [4 5 1 4 2 3 1 5]
 [0 8 0 5 0 8 0 9]
 [8 6 1 5 7 8 8 4]
 [0 4 0 5 0 1 0 2]
 [5 5 5 4 5 7 2 2]]


Créer un tableau `a` de taille  8x8 (8 lignes et 8 colonnes) rempli de valeurs aléatoires entières de 1 à 9 inclus puis mettre les cases $[1,3]$ et $[3,2]$ à 0 (en une seule instruction). 

In [9]:
a=np.random.randint(1,10,size=(8,8))
print(a)
a[[1,3],[3,2]]=0
print(a)

[[5 9 1 4 8 9 7 9]
 [5 5 2 1 8 2 8 4]
 [8 7 9 1 6 5 5 2]
 [3 2 3 9 1 6 1 4]
 [9 5 5 4 4 1 6 5]
 [2 8 3 6 7 5 9 7]
 [7 3 2 6 9 5 9 2]
 [8 9 9 3 9 2 8 7]]
[[5 9 1 4 8 9 7 9]
 [5 5 2 0 8 2 8 4]
 [8 7 9 1 6 5 5 2]
 [3 2 0 9 1 6 1 4]
 [9 5 5 4 4 1 6 5]
 [2 8 3 6 7 5 9 7]
 [7 3 2 6 9 5 9 2]
 [8 9 9 3 9 2 8 7]]


Créer un tableau `a` de taille  8x8 (8 lignes et 8 colonnes) rempli de valeurs aléatoires entières de 1 à 9 inclus puis mettre à 0 toutes les lignes pour lesquelles le vecteur `vect= np.array([False, True, True, False,False, 'True',False, 'True'])` vaut `True` (en une seule instruction). 

In [10]:
# A compléter ...
a=np.random.randint(1,10,size=(8,8))
print(a)
vect= np.array([False, True, True, False,False, True,False, True])
a[vect, :] = 0
display(a)


[[7 2 4 8 6 5 6 3]
 [7 1 6 3 3 9 2 2]
 [7 1 3 7 9 9 6 5]
 [9 3 8 8 9 1 5 2]
 [4 6 3 5 8 3 3 7]
 [1 1 2 4 5 8 1 6]
 [3 5 3 9 9 7 9 5]
 [9 9 5 3 4 4 6 8]]


array([[7, 2, 4, 8, 6, 5, 6, 3],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [9, 3, 8, 8, 9, 1, 5, 2],
       [4, 6, 3, 5, 8, 3, 3, 7],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [3, 5, 3, 9, 9, 7, 9, 5],
       [0, 0, 0, 0, 0, 0, 0, 0]])

A l'aide de la fonction np.ones,  créer un tableau carré de taille 7 ne contenant que des 1.
Puis en maximum deux lignes, faire un "damier" en remplaçant certains 1 par des 0 (voir résultat ci-dessous)

In [11]:
# A compléter ...
a=np.ones((7,7),dtype=int)
print(a)

[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]


### 3. Partage de  valeurs dans un tableau

#### a ) " Vues"   (extrait avec des slices) 

Créer un tableau `a` de taille 4x4 rempli de valeurs aléatoires entières de 1 à 9 inclus que l'on nommera a.

Créer ensuite une vue (appelée `b`) de la matrice `a` correspondant aux sélecteurs précédents en prenant pas ar exemple :

    b = a[0,:] 
    
    
Modifier le contenu de `b` et regarder l'effet sur `a`. Puis modifier `a` et regarder l'effet sur `b`

Exemple de ce qui est attendu :

    a= [[6 3 8 1]
     [3 9 4 4]
     [9 5 4 5]
     [4 2 9 8]] 
     b= [6 3 8 1]
    Après modification de la case 0,3 de a (mise à -1) et la case 0,0 de b (mise à 0)     on obtient :
    a= [[ 0  3  8 -1]
     [ 3  9  4  4]
     [ 9  5  4  5]
     [ 4  2  9  8]] 
     b= [ 0  3  8 -1]    

In [12]:
# A compléter ...
a=np.random.randint(1,10,size=(4,4))
display(a)
b=a[0,:]
display(b)
a[0, 3] = -1
b[0] = 0
display(a)

display(b)

array([[4, 1, 4, 6],
       [4, 4, 1, 6],
       [6, 7, 6, 4],
       [7, 6, 4, 1]])

array([4, 1, 4, 6])

array([[ 0,  1,  4, -1],
       [ 4,  4,  1,  6],
       [ 6,  7,  6,  4],
       [ 7,  6,  4,  1]])

array([ 0,  1,  4, -1])

In [15]:
# à compléter

# Créer un tableau 4x4 rempli de valeurs aléatoires entières de 1 à 9 inclus
a = np.random.randint(1, 10, (4, 4))

# Afficher le tableau a
print("a =", a)

# Créer une copie b de la première ligne de a
b = a[0, :].copy()

# Afficher la copie b
print("b =", b)

# Modifier la première valeur de b et afficher a
b[3] = -1
print("Après modification de la case 0,3 de b (mise à -1), a devient :\n", a)

# Modifier la première valeur de a et afficher b
a[0, 0] = 0
print("Après modification de la case 0,0 de a (mise à 0), b devient :\n", b)


a = [[5 1 4 2]
 [1 2 7 4]
 [4 6 2 8]
 [3 5 5 6]]
b = [5 1 4 2]
Après modification de la case 0,3 de b (mise à -1), a devient :
 [[5 1 4 2]
 [1 2 7 4]
 [4 6 2 8]
 [3 5 5 6]]
Après modification de la case 0,0 de a (mise à 0), b devient :
 [ 5  1  4 -1]


In [14]:
# A compléter ...

### 4) Tableaux de tailles différentes

Créer un array numpy nommé `a` de taille 3x3 contenant des valeurs aléatoires entières entre 1 et 9 comprises. 

Créer un second array nommé `b` de taille 1x3 également rempli de valeurs aléatoires entières entre 1 et 9 comprises.

Créer un troisième array nommé `c` de taille 3x1 également rempli de valeurs aléatoires entières entre 1 et 9 comprises.illes différentes

In [31]:
# A compléter ...
a=np.random.randint(1,10,size=(3,3))
display(a)
b=np.random.randint(1,10,size=(1,3))
display(b)
c=np.random.randint(1.10,size=(3,1))
display(c)

array([[5, 1, 3],
       [6, 6, 6],
       [8, 7, 4]])

array([[4, 4, 1]])

array([[0],
       [0],
       [0]])

Ajouter la constante 5 à a, afficher le résultat :

In [32]:
# A compléter ...
a=a+5
display(a)

array([[10,  6,  8],
       [11, 11, 11],
       [13, 12,  9]])

Calculer (a+b). Que représente ce calcul?

Calculer (a+c). Que représente ce calcul?

Afficher b.T

En déduire une façon d'ajouter b à chaque colonne de a

In [33]:
# A compléter ...
cal1=a+b
print(cal1)
cal2=a+c
print(cal2)
print(b.T)
resultat = a + b.T
print(resultat)

[[14 10  9]
 [15 15 12]
 [17 16 10]]
[[10  6  8]
 [11 11 11]
 [13 12  9]]
[[4]
 [4]
 [1]]
[[14 10 12]
 [15 15 15]
 [14 13 10]]


Calculer la somme b+c, afficher le résultat et le commenter.

In [34]:
# A compléter ...
cal3=b+c
print(cal3)

[[4 4 1]
 [4 4 1]
 [4 4 1]]


### 5. Exercice récapitulatif
On regroupe dans une liste de listes les notes de 50 étudiants. Il y a 20 notes par étudiant.



In [35]:
tabNotes=[[ 4,  4,  13, 9, 11,  8, 11, 8,  0,  6, 6,  12,  5,  9,  6,  8,
         3, 11, 10, 11],
       [5, 11, 9,  2,  6,  7, 6,  6, 11, 11,  1, 10, 11, 7, 14, 10,
         9, 12,  7,  5],
       [15, 16,  12,  10, 13, 10, 11, 14,  6,  6,  13,  8, 11, 12, 10,  9,
        10,  12, 12,  12],
       [12, 17, 14,  13, 12, 17,  13, 14,  15, 16, 15,  15,  12,  16,  13, 20,
         12, 14,  14, 19],
       [6,  7,  5, 13,  6,  9,  10,  10,  9,  8, 7,  0, 6,  6, 13, 13,
        10,  4, 16, 13],
       [ 5,  4,  6,  9, 11, 13,  6,  7, 10,  8,  6, 13, 11, 11, 11, 15,
        10, 10,  9,  8],
       [ 11, 7, 12, 10, 10,  6,  5, 8,  10,  3, 9, 11,  8,  7, 11,  4,
         6, 12,  4,  7],
       [10, 10, 11,  5,  9, 10, 16,  5,  5,  4, 13, 14, 12,  2, 16,  5,
        11,  8,  9,  6],
       [ 2, 5, 7,  3,  4, 16, 12,  8,  0, 9, 10, 10,  9,  3,  4,  3,
        10, 7, 12, 10],
       [ 4, 10, 13,  8,  8,  7, 10,  3,  8,  6,  0, 15, 12, 11, 12, 15,
        11, 13, 15,  4],
       [15,  11,  10, 16, 14,  17, 19, 17, 16,  16, 17, 14, 12,  17,  12, 14,
         17, 17,  13,  12],
       [6, 7,  4, 14,  8, 11,  9,  7, 12,  6,  8, 11,  10, 9,  13, 9,
         12,  9, 10, 10],
       [20, 14, 17, 17, 16,  13, 17, 15,  17, 14,  10, 17,  14,  13,  19, 15,
         13, 19, 15,  18],
       [ 3, 14, 11,  3,  11,  8,  2, 11,  4,  5, 12, 17,  3,  3,  9, 13,
        12,  3,  5, 10],
       [ 5, 10, 10, 11, 9, 12,  0,  5,  2, 12, 9,  9,  1,  4, 10,  9,
        10,  1, 10, 13],
       [10,  8,  8, 19, 13,  6,  5, 16, 16,  10, 17,  10,  3, 15, 13, 14,
         5, 14, 12,  9],
       [ 9, 10, 10, 10, 13, 10, 12,  7, 10, 10, 11, 15,  5,  7,  0,  7,
        12, 10, 13, 13],
       [ 6,  7,  2, 11,  1, 11,  11, 11,  6,  0, 10, 14, 12,  12,  9,  13,
        18,  10, 18, 20],
       [14,  13, 19,  10,  17, 15,  10,  15,  12, 13,  7,  8,  13, 11,  9, 18,
        13, 13,  5, 18],
       [4,  1,  6, 17,  4,  7,  5, 19, 11,  5,  7, 18, 16,  8,  9, 11,
        10, 10,  1, 12],
       [12, 12,  12,  6,  6, 15, 11, 12, 12, 10, 11, 11, 12, 11,  9, 11,
         5, 7,  12, 12],
       [ 7, 5, 13, 11,  9, 11,  6, 10, 12, 10, 17, 10,  5,  4,  9, 11,
        10,  3, 11,  5],
       [10,  6, 10,  4, 8,  4,  5,  4,  4, 8, 7, 9,  4, 9, 5, 8,
         4,  2,  7,  3],
       [14,  9,  3, 13,  5, 11,  6, 12, 10,  7, 12,  6, 13,  8,  0,  5,
        14, 13, 12, 11],
       [10,  4,  5,  3,  7, 15,  8,  0,  7,  8,  0,  5,  4, 12,  8,  4,
        13, 12, 14, 11],
       [11,  8, 11, 11,  10, 14,  2, 11, 10, 12,  10,  9, 10,  8,  9, 12,
        10, 10, 7,  7],
       [ 5,  4, 5,  13, 7,  7,  9, 10,  6, 11, 13, 12,  8,  9,  3,  0,
        10,  9, 11, 14],
       [11, 11, 11,  10,  10, 10,  7,  12,  7, 14,  6,  13, 11,  12, 8, 7,
        12,  12,  8, 11],
       [11, 10,  8,  6, 11,  8,  8, 14,  11, 12,  12, 11,  11,  10, 10, 8,
         13,  9,  5, 11],
       [17, 17, 14, 15,  13, 12, 15,  15, 15, 16, 16, 12,  14, 15, 14, 11,
         6, 13,  12, 10],
       [16, 13, 15, 13,  11,  10, 14,  12,  10,  12, 16,  16,  16,  16, 10, 10,
         10,  11,  11,  11],
       [12, 12,  8,  8,  9,  9, 15,  9,  9, 9,  9,  7, 13, 10, 9, 14,
         5, 12,  10,  5],
       [16,  9,  10,  8, 17, 13, 16, 13,  7,  9, 17, 10, 16, 11,  7, 11,
        10,  6, 12, 12],
       [10,  5,  5,  6,  7,  2, 10, 13, 17, 12, 10, 12, 16,  10, 13,  5,
        10,  7, 10,  8],
       [ 3, 12,  8, 9, 9, 12,  2, 12,  3,  7,  1, 10,  6, 9,  5,  7,
         2,  5, 15, 10],
       [14, 12,  9, 12,  9, 8, 12, 10,  9, 13, 13,  8,  2, 13,  11,  11,
         13, 7,  11,  11],
       [ 11, 8,  9, 14, 16,  3, 16,  4,  5, 13, 12,  11, 9,  7, 7, 16,
        14, 10, 16,  6],
       [11,  4,  5,  10,  4,  5, 10, 10, 14,  4, 12,  6,  7,  9, 16,  8,
        10, 9, 9,  13],
       [16, 18, 10, 18, 11, 12, 19, 13,  4,  6,  16, 17, 17, 10,  7, 16,
        10, 10,  3,  1],
       [ 7, 12,  9, 12, 9,  12,  4, 13, 13,  3,  12,  9, 14, 19, 12,  0,
         3, 6, 13, 13],
       [14, 10, 10,  9,  6, 12, 18, 18, 14, 14, 10, 18,  10, 10,  10,  12,
        19,  5, 14,  0],
       [20, 20,  1,  7,  5, 15,  5, 8, 9,  8,  7, 8, 8, 16,  0,  3,
         3, 13,  3,  6],
       [ 4,  6,  1, 2, 13,  2, 9, 6, 10, 12, 12,  2,  4,  10, 14,  10,
         6, 15, 10,  5],
       [ 3, 7,  3,  4, 10,  3, 10, 13,  7,  5,  3,  4, 2,  8, 11,  8,
         9,  6,  7,  3],
       [20, 14,  9, 13,  6, 5, 8,  4,  4, 11,  6,  11,  12, 11, 10,  4,
         7, 8,  9,  11],
       [ 8, 10,  2,  8,  5, 10,  10,  0, 7,  7,  6, 14, 13,  4, 7,  8,
         6, 8, 12,  3],
       [ 8, 12,  7,  9, 14, 12, 12, 12, 13, 13,  9,  7,  4, 10,  8, 11,
         6, 15,  0, 15],
       [ 7, 11,  7, 11,  6,  7, 10,  8,  1, 14, 12, 13, 10,  8, 15, 12,
        7, 10, 14,  4],
       [18,  9, 14,  5, 14,  6, 12,  8,  12,  10, 9,  8, 9,  0,  4, 15,
        11, 10,  12,  7],
       [ 20,  6, 10,  12,  5,  4,  13,  8, 12, 12,  13, 12, 17,  8,  9,  0,
        10,  13,  12,  13]]

1.Transformer ce tableau en array numpy. Vérifier qu'on a bien un tableau à 50 lignes et 20 colonnes.

Calculer la moyenne globale des toutes les notes puis la moyenne des toues les notes non nulles.

In [37]:
# A compléter ...
ta=np.array(tabNotes) 
moy=np.mean(ta)
print(moy)
cal=ta[ta!=0]
moy1=np.mean(cal)
print(moy1)

9.714
9.892057026476579


2.a. Calculer le tableau des  50 moyennes des des étudiants à chaque test.

b. Calculer le tableau des 20 notes moyennes pour chaque des 20 tests.


In [40]:
# A compléter ...
moy2=np.mean(ta,axis=0)
print(moy2)
moy3=np.mean(ta,axis=1)
print(moy3)

[10.24  9.64  8.86  9.84  9.36  9.64  9.84 10.    9.08  9.4   9.94 10.84
  9.66  9.6   9.46  9.66  9.64  9.7  10.24  9.64]
[ 7.75  8.   11.1  14.65  8.55  9.15  8.05  9.05  7.2   9.25 14.8   9.25
 15.65  7.95  7.6  11.15  9.7  10.1  12.65  9.05 10.45  8.95  6.05  9.2
  7.5   9.6   8.3  10.15  9.95 13.6  12.65  9.7  11.5   9.4   7.35 10.4
 10.35  8.8  11.7   9.75 11.65  8.25  7.65  6.3   9.15  7.4   9.85  9.35
  9.65 10.45]


3.a. Pour chacun des 20 tests, compter combien d'étudiants ont la moyenne et afficher les résultats

3.b. Compter pour chaque étudiant combien de fois il a eu la moyenne

In [43]:
# A compléter ...
moyenne_reussite = 10
moy4 = np.sum(ta >= moyenne_reussite, axis=0)
print("Nombre d'étudiants ayant la moyenne pour chaque test :")
print(moy4)

moy5 = np.sum(ta >= moyenne_reussite, axis=1)
print("Nombre de tests où chaque étudiant a eu la moyenne :")
print(moy5)


Nombre d'étudiants ayant la moyenne pour chaque test :
[29 27 24 28 23 28 29 29 26 26 29 33 29 26 25 27 33 29 33 30]
Nombre de tests où chaque étudiant a eu la moyenne :
[ 7  8 16 20  8 10  8 10  7 11 20  9 20  9  9 13 14 13 16  9 15 11  2 11
  7 13  8 14 13 19 20  8 14 12  6 13 11  9 15 11 16  5  9  4  9  6 11 11
 10 13]


4. Afficher le numéro de l'étudiant qui a la meilleure moyenne sur les 20 tests et celui qui a la moins bonne (ainsi que les moyennes correspondantes).

In [47]:
# A compléter ...
# Calculer les moyennes des étudiants sur les 20 tests
moyennes = np.mean(ta, axis=1)


indice1 = np.argmax(moyennes)

# Trouver l'indice de l'étudiant ayant la moins bonne moyenne
indice2= np.argmin(moyennes)

# Afficher les résultats
print("Étudiant avec la meilleure moyenne :")
print("Numéro de l'étudiant :", indice1)
print("Moyenne correspondante :", moyennes[indice1])

print("\nÉtudiant avec la moins bonne moyenne :")
print("Numéro de l'étudiant :", indice2)
print("Moyenne correspondante :", moyennes[indice2])



Étudiant avec la meilleure moyenne :
Numéro de l'étudiant : 12
Moyenne correspondante : 15.65

Étudiant avec la moins bonne moyenne :
Numéro de l'étudiant : 22
Moyenne correspondante : 6.05


5. Calculer et afficher le numéro de l'étudiant qui a le plus de notes supérieures à 14.

In [48]:
# A compléter ...
# Compter le nombre de notes supérieures à 14 pour chaque étudiant
notes= np.sum(ta> 14, axis=1)

# Trouver l'indice de l'étudiant ayant le plus de notes supérieures à 14
indice3 = np.argmax(notes)

# Afficher le résultat
print("Étudiant avec le plus de notes supérieures à 14 :")
print("Numéro de l'étudiant :", indice3)
print("Nombre de notes supérieures à 14 :", notes[indice3])


Étudiant avec le plus de notes supérieures à 14 :
Numéro de l'étudiant : 12
Nombre de notes supérieures à 14 : 13


6. On veut corriger quelques erreurs de saisie
- l'étudiant de la ligne d'indice 5 a dix points de plus pour sa dernière note
- pour le test de la première colonne (colonne 0) , il faut ajouter 2 points à tous les étudiants
- ensuite il faut remettre à 20 les notes qui dépasseraient 20

In [52]:
# A compléter ...
ta1= np.copy(ta)
ta1[5,-1]+=10
ta1[:,0]+=2
ta1[ta1 > 20] = 20
print(ta1)


[[ 6  4 13  9 11  8 11  8  0  6  6 12  5  9  6  8  3 11 10 11]
 [ 7 11  9  2  6  7  6  6 11 11  1 10 11  7 14 10  9 12  7  5]
 [17 16 12 10 13 10 11 14  6  6 13  8 11 12 10  9 10 12 12 12]
 [14 17 14 13 12 17 13 14 15 16 15 15 12 16 13 20 12 14 14 19]
 [ 8  7  5 13  6  9 10 10  9  8  7  0  6  6 13 13 10  4 16 13]
 [ 7  4  6  9 11 13  6  7 10  8  6 13 11 11 11 15 10 10  9 18]
 [13  7 12 10 10  6  5  8 10  3  9 11  8  7 11  4  6 12  4  7]
 [12 10 11  5  9 10 16  5  5  4 13 14 12  2 16  5 11  8  9  6]
 [ 4  5  7  3  4 16 12  8  0  9 10 10  9  3  4  3 10  7 12 10]
 [ 6 10 13  8  8  7 10  3  8  6  0 15 12 11 12 15 11 13 15  4]
 [17 11 10 16 14 17 19 17 16 16 17 14 12 17 12 14 17 17 13 12]
 [ 8  7  4 14  8 11  9  7 12  6  8 11 10  9 13  9 12  9 10 10]
 [20 14 17 17 16 13 17 15 17 14 10 17 14 13 19 15 13 19 15 18]
 [ 5 14 11  3 11  8  2 11  4  5 12 17  3  3  9 13 12  3  5 10]
 [ 7 10 10 11  9 12  0  5  2 12  9  9  1  4 10  9 10  1 10 13]
 [12  8  8 19 13  6  5 16 16 10 17 10  3 15 13 14  5 14

7. Extraire et afficher les résultats du test 5  (colonne d'indice 4)

In [53]:
# A compléter ...
col=ta1[:,4]
print(col)



[11  6 13 12  6 11 10  9  4  8 14  8 16 11  9 13 13  1 17  4  6  9  8  5
  7 10  7 10 11 13 11  9 17  7  9  9 16  4 11  9  6  5 13 10  6  5 14  6
 14  5]


8. Utiliser np.unique pour voir quelle est la note la plus souvent obtenue à ce test et quelles notes ne sont pas obtenues.

Note la plus souvent obtenue : 20
Notes non obtenues : [False  True False False False False False False False False False False
 False False False False False False False False False]


9. Utiliser np.where pour récupérer les numéros des étudiants qui ont eu plus de 12  ce test.

In [60]:
# A compléter ...
etudiants_plus_de_12 = np.where(ta1 > 12)
print(etudiants_plus_de_12)


(array([ 0,  1,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  4,  4,  4,  4,  4,  5,  5,  5,  5,  6,
        7,  7,  7,  7,  8,  9,  9,  9,  9,  9, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 11, 11, 12, 12, 12, 12, 12, 12, 12,
       12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 13, 13, 13, 14, 15,
       15, 15, 15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 17, 17, 17, 17, 17,
       18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 19, 19, 19, 19, 20,
       20, 21, 21, 23, 23, 23, 23, 23, 24, 24, 24, 25, 25, 26, 26, 26, 27,
       27, 27, 28, 28, 28, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29,
       29, 29, 30, 30, 30, 30, 30, 30, 30, 30, 30, 31, 31, 31, 31, 32, 32,
       32, 32, 32, 32, 32, 33, 33, 33, 33, 34, 35, 35, 35, 35, 35, 36, 36,
       36, 36, 36, 36, 36, 36, 37, 37, 37, 37, 38, 38, 38, 38, 38, 38, 38,
       38, 38, 39, 39, 39, 39, 39, 39, 40, 40, 40, 40, 40, 40, 40, 40, 41,
       41, 41, 41, 41, 4