# TP9 -- Retour sur la logique -- Matrices avec numpy ou sympy

## Partie Logique

Les valeurs Booléennes qui représentent le vrai et le faux sont True et False. Les opérations logiques
utilisées sont :  
- AND  &  : a & b
- OR  | :  a | b
- NOT  ~  : ~a
- => : a >> b

1) Représentez la formule:  $F = ((p \to q) \vee(r \wedge \neg p)) \wedge \neg(q \wedge r)$ 

où p,q,r sont des variables propositionnelles donc des symboles

In [1]:
import sympy as sy
# à compléter
p,q,r=sy.symbols('p,q,r')
f=((p>>q)|(r&~p))&(q&r)
sy.pprint(f)
display(f)
print(f)

q ∧ r ∧ ((r ∧ ¬p) ∨ (p → q))


q & r & ((Implies(p, q)) | (r & ~p))

q & r & ((Implies(p, q)) | (r & ~p))


2) Que vaut F quand p est vrai, q aussi et r faux? Et quand p est vrai, q et r sont faux?

In [2]:
# à compléter
premier=f.subs({p:True,q:True,r:False})
print(premier)
deuxieme=f.subs({p:True,q:False,r:False})
print(deuxieme)

False
False


3) On peut aussi mélanger valuation et variables: Que sera le résultat de $f$ si on substitue FAUX à la variable q ?

In [3]:
# à compléter
f.subs({q:False})


False

4) Faire la table de vérité de F  (on écrira une boucle)

In [4]:
# à compléter
for (a,b,c) in [(i,j,k)for i in(True,False) for j in (True,False) for k in(True,False)]:
    print(a,b,c,f.subs({p:a,q:b,r:c}))

True True True True
True True False False
True False True False
True False False False
False True True True
False True False False
False False True False
False False False False


5. Mise sous forme normale: toute expression peut être mise sous forme normale
- d'une conjonction de disjonctions (FN conjonctive)
- d'une disjonction de conjonctions (FN disjonctive)

Pour trouver la FN conjonctive (resp. disjonctive) de F, on fait appel à la fonction to_cnf (resp.
to_dnf ) de sympy

 Donner les FNC et FND de F

In [5]:
# à compléter
fnc=sy.to_cnf(f)
print(fnc)
fnd=sy.to_dnf(f)
print(fnd)

q & r & (q | ~p) & (q | r | ~p)
(q & r) | (q & r & ~p)


6) Simplifier F

In [6]:
# à compléter
simpli=sy.simplify(f)
print(simpli)

q & r


7. On considère la formule $F$ donnée par sa table de vérité dont la dernière colonne est dans l'ortdre usuel

10101100

Donner deux formules qui ont cette table de vérité (une conjonctive et une disjonctive)

In [7]:
# à compléter
min=[[0,0,0],[0,1,0],[0,0,1],[1.01]]

## Calcul matriciel

Ce TP présente l'objet spécifique matrix, défini dans NumPy et SymPy pour supporter les matrices et les opérations associées. On y voit également en quoi ces modules sont adaptés à l'algèbre linéaire, en facilitant la résolution de systèmes d'équations linéaires, par exemple, grâce aux opérations efficaces sur les matrices.


In [8]:
import numpy as np
import sympy as sp
import warnings
warnings.filterwarnings('ignore')


## Création de matrices

Une matrice se représente en NumPy à l'aide d'un objet matrix. Il s'agit en fait d'une sous-classe de ndarray, c'est-à-dire que tout ce que l'on a vu sur les atableaux (arrays) s'applique également aux objets matrix. La manière la plus immédiate de créer une matrice consiste à utiliser la fonction **np.matrix**. Une autre façon de créer une matrice consiste à transformer un tableau multidimensionnel à l'aide de la fonction **np.mat**

Le résultat attendu est un objet matrix, ou plus précisément un objet numpy.matrixlib.defmatrix.matrix, qui est également une instance de la classe ndarray.

1. Créer les matrices suivantes (en utilisant np.mat et en utilisant matrix):

$A = \begin{bmatrix}1 & 0 & 0\\
2 & -2 & 1\\
0& -3 & 3
\end{bmatrix}
\;\;\;    
B = \begin{bmatrix}1 & 2 & 0\\
0 & -2 & 2\\
1& -1 & 1
\end{bmatrix}
\;\;\;
C = \begin{bmatrix}1 & 2 & 3\\
1& -1 & 1
\end{bmatrix}
\;\;\;et\;\;\;\; 
D = \begin{bmatrix}1 & 2 & 3\\
2 & 4 & 6\\
3& 6 & 9
\end{bmatrix}
$

In [41]:
# à compléter

import numpy as np
# Création de la matrice A
A = np.mat([[1, 2, 0], [-2, -3, 0], [1, 3, 0]])

# Création de la matrice B
B = np.mat([[1, 0, 1], [2, -2, -1], [0, 2, 1]])

# Création de la matrice C
C = np.mat([[1, 1, 2], [-1, -3, 3]])

# Création de la matrice D
D = np.mat([[1, 2, 3], [4, 6, 9], [3, 6, 9]])

print("Matrice A:")
print(A)
print("\nMatrice B:")
print(B)
print("\nMatrice C:")
print(C)
print("\nMatrice D:")
print(D)


Matrice A:
[[ 1  2  0]
 [-2 -3  0]
 [ 1  3  0]]

Matrice B:
[[ 1  0  1]
 [ 2 -2 -1]
 [ 0  2  1]]

Matrice C:
[[ 1  1  2]
 [-1 -3  3]]

Matrice D:
[[1 2 3]
 [4 6 9]
 [3 6 9]]


In [42]:
# à compléter
A=np.matrix([[1, 2, 0], [-2, -3, 0], [1, 3, 0]])
B=np.matrix([[1, 0, 1], [2, -2, -1], [0, 2, 1]])
C=np.matrix([[1, 1, 2], [-1, -3, 3]])
D=np.matrix([[1, 2, 3], [4, 6, 9], [3, 6, 9]])




On peut créer facilement des matrices particulières comme les matrices identité ou des matrices nulles.
Créer les matrices identité de taille  3 et la matrice nulle à 3 lignes et 4  colonnes.
On affichera le type obtenu.

In [43]:
# à compléter
import numpy as np

# Création de la matrice nulle de 3 lignes et 4 colonnes
matrice_nulle_3_4 = np.zeros((3, 4))

# Affichage de la matrice nulle
print("Matrice nulle de 3 lignes et 4 colonnes :")
print(matrice_nulle_3_4)

# Affichage du type
print("Type de la matrice nulle :", type(matrice_nulle_3_4))

import numpy as np

# Création de la matrice identité de taille 3
matrice_identite_3 = np.eye(3)

# Affichage de la matrice identité
print("Matrice identité de taille 3 :")
print(matrice_identite_3)

# Affichage du type
print("Type de la matrice identité :", type(matrice_identite_3))



Matrice nulle de 3 lignes et 4 colonnes :
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Type de la matrice nulle : <class 'numpy.ndarray'>
Matrice identité de taille 3 :
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Type de la matrice identité : <class 'numpy.ndarray'>


## Propriétés: 
#### Taille 
- Afficher la taille de la matrice A (sa dimension) et vérifier que la matrice A est bien une matrice carrée

In [44]:
# à compléter
taille_A = A.shape
print("Taille de la matrice A :", taille_A)

# Vérifier si la matrice A est carrée
est_carree = A.shape[0] == A.shape[1]
if est_carree:
    print("La matrice A est une matrice carrée.")
    
else:
    print("La matrice A n'est pas une matrice carrée.")
   

Taille de la matrice A : (3, 3)
La matrice A est une matrice carrée.


#### Diagonale principale
- Afficher la diagonale principale de la matrice A (c'est-à-dire les éléments (a)ij tels que i=j). 
- Afficher ensuite les autres diagonales au-dessus et en-dessous de la diagonale principale


In [45]:
# à compléter
# Afficher la diagonale principale
diagonale_principale = np.diag(A)
print("Diagonale principale de la matrice A :\n", diagonale_principale)

# Afficher les diagonales au-dessus de la diagonale principale
diagonales_au_dessus = [np.diag(A, k=i) for i in range(1, A.shape[0])]
print("Diagonales au-dessus de la diagonale principale de la matrice A :\n", diagonales_au_dessus)

# Afficher les diagonales en-dessous de la diagonale principale
diagonales_en_dessous = [np.diag(A, k=-i) for i in range(1, A.shape[0])]
print("Diagonales en-dessous de la diagonale principale de la matrice A :\n", diagonales_en_dessous)

Diagonale principale de la matrice A :
 [ 1 -3  0]
Diagonales au-dessus de la diagonale principale de la matrice A :
 [array([2, 0]), array([0])]
Diagonales en-dessous de la diagonale principale de la matrice A :
 [array([-2,  3]), array([1])]


### Trace

- Calculer la trace de la matrice carrée A (avec **np.trace**) et vérifier qu'elle est égale à la somme des éléments de sa diagonale principale.

In [46]:
# à compléter


# Calculer la trace de la matrice A
trace_A = np.trace(A)

# Calculer la somme des éléments de la diagonale principale
somme_diagonale_principale = np.sum(np.diag(A))

# Vérifier si la trace est égale à la somme des éléments de la diagonale principale
verification = trace_A == somme_diagonale_principale

# Afficher la trace de A et la vérification
print("Trace de A :", trace_A)
print("Vérification :", verification)


Trace de A : -2
Vérification : True


### Rang
- Le rang d'une matrice s'obtient avec la fonction **np.linalg.matrix_rank** qui représente notamment le nombre de lignes linéairement indépendantes d'une matrice. Calculer le rang des trois matrices B,C et D :

In [47]:
# à compléter
# Création de la matrice A
# Calculer le rang de la matrice B
rang_B = np.linalg.matrix_rank(B)

# Calculer le rang de la matrice C
rang_C = np.linalg.matrix_rank(C)

# Calculer le rang de la matrice D
rang_D = np.linalg.matrix_rank(D)

# Afficher les rangs
print("Rang de la matrice B :", rang_B)
print("Rang de la matrice C :", rang_C)
print("Rang de la matrice D :", rang_D)

Rang de la matrice B : 3
Rang de la matrice C : 2
Rang de la matrice D : 2


### Déterminant
- Le calcul du déterminant, uniquement défini sur les matrices carrées, intervient notamment dans la résolution de systèmes d'équations linéaires. On l'obtient avec la fonction **np.linalg.det**. 

Calculer les déterminants des matrices A et B:

In [48]:
# à compléter
 
determinant_A = np.linalg.det(A)

# Afficher le déterminant
print("Déterminant de la matrice A :", determinant_A)


determinant_B= np.linalg.det(B)

# Afficher le déterminant
print("Déterminant de la matrice B :", determinant_B)

Déterminant de la matrice A : 0.0
Déterminant de la matrice B : 4.0


### Transposée
- Calculer la transposée d'une matrice revient à construire une nouvelle matrice dont les lignes sont les colonnes de la matrice originale, et vice-versa. Calculer la transposée de la matrice A :

In [51]:
# à compléter
# Supposons que A soit votre matrice
A_transpose = A.transpose()

# Afficher la transposée de la matrice A
print("Transposée de la matrice A :\n", A_transpose)

# Supposons que A soit votre matrice
B_transpose = B.transpose()

# Afficher la transposée de la matrice A
print("Transposée de la matrice B :\n", B_transpose)

Transposée de la matrice A :
 [[ 1 -2  1]
 [ 2 -3  3]
 [ 0  0  0]]
Transposée de la matrice B :
 [[ 1  2  0]
 [ 0 -2  2]
 [ 1 -1  1]]


### Produit

Tout comme pour les vecteurs, différentes possibilités existent pour le produit de matrices. Ces différentes opérations sont évidemment supportées par Numpy.


#### Produit matriciel
- Étant donné deux matrices compatibles, c'est-à-dire que le nombre de colonnes de la première est égal au nombre de lignes de la seconde, on peut effectuer un produit matriciel entre ces deux matrices. 

Attention à ne pas confondre A*B pour les tableaux et np.dot(A,B)

In [53]:
# à compléter
produit=A*B
display(produit)

dot=np.dot(A,B)
display(dot)

matrix([[ 5, -4, -1],
        [-8,  6,  1],
        [ 7, -6, -2]])

matrix([[ 5, -4, -1],
        [-8,  6,  1],
        [ 7, -6, -2]])

Calculer le produit matriciel entre les différentes matrices si elles sont de tailles compatibles et voir ce qui se produit si les matrices ne sont pas de tailles compatibles.

In [55]:
# à compléter
#print(A[:,:2]*C)
#print ("si on demande CA qui n'est pas calculable il se produira une erreur  ")
#np.dot(A,C) 

# Vérifier si le produit matriciel entre C et A est possible
if C.shape[1] == A.shape[0]:
    product_CA = np.dot(C, A)
    print("Produit matriciel entre C et A :\n", product_CA)
else:
    print("Le produit matriciel entre C et A n'est pas possible car le nombre de colonnes de C n'est pas égal au nombre de lignes de A.")




Produit matriciel entre C et A :
 [[ 1  5  0]
 [ 8 16  0]]


### Inverse

- Une autre opération très importante en algèbre linéaire, notamment pour résoudre des systèmes d'équations linéaires, consiste à calculer l'inverse d'une matrice carrée. Si la matrice est inversible, alors on peut obtenir son inverse avec l'attribut I. 


Vérifier si la matrice A est inversible, afficher son inverse et vérifier que le produit de A avec son inverse donne la matrice identité

In [56]:
# à compléter
# Vérifier si la matrice A est inversible
if np.linalg.det(A) != 0:
    # Calculer l'inverse de A
    A_inv = np.linalg.inv(A)
    
    # Afficher l'inverse de A
    print("Inverse de A :\n", A_inv)
    
    # Calculer le produit de A avec son inverse
    product_A_A_inv = np.dot(A, A_inv)
    
    # Afficher le produit de A avec son inverse
    print("Produit A * A.I :\n", product_A_A_inv)
    
    # Vérifier si le produit est proche de la matrice identité
    verification = np.allclose(product_A_A_inv, np.eye(A.shape[0]))
    
    # Afficher le résultat de la vérification
    print("Vérification  :\n", verification)
else:
    print("La matrice A n'est pas inversible.")



La matrice A n'est pas inversible.


Pour s'en sortir lorsque l'on fait des calculs en nombres flottants, il ne faut jamais comparer deux valeurs avec l'opérateur d'égalité. Une solution pour comparer deux matrices de float consiste à utiliser la fonction allclose qui permet de faire une égalité approximative :

In [21]:
print("Vérification avec np.allclose:")
print(np.allclose(A * A.I, np.identity(3)))

Vérification avec np.allclose:
True


#### Changement de base :
Si A est la matrice d'origine et P la matrice de passage on peut calculer B matrice dans la nouvelle base avec $B=P^{-1}AP$

In [57]:
A=np.matrix([[1,0,0,-2],[2,-2,2,0],[0,-3,3,6],[1,0,0,-2]])
P = np.matrix([[2,0,0,1],[4,1,2,2],[2,1,3,0],[1,0,0,1]])

# à compléter
# Calculer l'inverse de P
P_inv = np.linalg.inv(P)


# Calculer B dans la nouvelle base
B = np.dot(P_inv, np.dot(A, P))

# Afficher la matrice B
print("Matrice B dans la nouvelle base :\n", B)

Matrice B dans la nouvelle base :
 [[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0. -1.]]


# Systèmes d'équations linéaires

Résoudre un système d'équations linéaires revient à résoudre une équation de la forme $A\cdot X=B$ où $A$ est la matrice du systeme et $X$ et $B$ deux matrices colonnes. On déduit que la solution est simplement $X= A^{−1} \cdot B $ sous certaines conditions.

- Résoudre le système suivant :

\begin{cases}
3x+y-z  &=2 \\
-x-y +z&=0\\
2x+y +z&=3\\
\end{cases}

Le systeme devient $A\cdot X=B$ 

In [23]:
# à compléter


sans  arrondi  x= 1.0  y= 1.6653345369377346e-16  z= 1.0

avec arrondi : x= 1.0  y= 0.0  z= 1.0


In [24]:
A=np.array([[3,1,-1],[-1,-1,1],[2,1,1]])
B=np.array([[2],[0],[3]])
C=np.array([2,0,3])
# à compléter

matrice A 
 [[ 3  1 -1]
 [-1 -1  1]
 [ 2  1  1]]

matrice B 
 [[2]
 [0]
 [3]]

matrice C 
 [2 0 3]

solve A,B
  [[1.00000000e+00]
 [1.66533454e-16]
 [1.00000000e+00]]

avec arrondi : 
  [[1.]
 [0.]
 [1.]]

solve A, C 
 [1.00000000e+00 1.66533454e-16 1.00000000e+00]

avec arrondi 
  [1. 0. 1.]


Résoudre l'équation suivante : (Résolution approximative)
\begin{cases}
x+2y  &=1 \\
2x+4y &=0
\end{cases}

In [25]:
# à compléter

Determinant de A: 0.0


Heureusement, tout n'est pas perdu. On peut, en effet, obtenir une solution approximative, qui va faire en sorte que Ax soit le plus proche possible de b, c'est-à-dire une solution qui va minimiser b−Ax. Pour cela, il suffit d'utiliser la fonction lstsq du module scipy.linalg, à qui on passe en paramètres les matrices A et b, comme ci-dessous :

In [26]:
# à compléter

Solutions proches :
x= 0.04  y= 0.08


Résoudre l'équation suivante : x +y =2

On va, en fait, obtenir une des solutions acceptables pour le système :

In [27]:
# à compléter

Une solution acceptable :
[[1.]
 [1.]]


# Matrices avec sympy

On peut aussi utiliser sympy pour travailler avec les matrices.
Ceci permet en plus d'utiliser des symboles et de calculer avec des symboles.

1. Créer les  matices suivantes  puis calculer les déterminants.
On pourra utiliser factor pour factoriser les déterminants.

$A = \begin{bmatrix}-1-a & 4 & 2\\
2& 1-a & -1\\
-2 & 0 & 2-a
\end{bmatrix}
\;\;\;
B = \begin{bmatrix}-1 & 3 & a\\
-2 & 4 & a\\
2& -2 & -1
\end{bmatrix}
\;\;\;et\;\;\;\; 
C = \begin{bmatrix}1 & 1 & 1\\
1 & a & a\\
1& 1 & a
\end{bmatrix}
$


In [28]:
a# à compléter

In [29]:
# à compléter

Matrix([
[-a - 1,     4,     2],
[     2, 1 - a,    -1],
[    -2,     0, 2 - a]])

determinant de la matrice  -a**3 + 2*a**2 + 5*a - 6
determinant de la matrice  -(a - 3)*(a - 1)*(a + 2)


In [30]:
B=sp.Matrix([[-1,3,a],[-2,4,a],[2,-2,-1]])
display(B)
da=B.det()
print("determinant de la matrice B ",da)
# à compléter

Matrix([
[-1,  3,  a],
[-2,  4,  a],
[ 2, -2, -1]])

determinant de la matrice B  -2


In [31]:
# à compléter

Matrix([
[1, 1, 1],
[1, a, a],
[1, 1, a]])

determinant de la matrice  a**2 - 2*a + 1
determinant de la matrice  (a - 1)**2


In [32]:
# à compléter

inverse de C quand c'est possible 


Matrix([
[ a/(a - 1), -1/(a - 1),          0],
[         0,  1/(a - 1), -1/(a - 1)],
[-1/(a - 1),          0,  1/(a - 1)]])

## Résolution de systèmes linéaires

- Résoudre le système suivant : (avec une solution)

\begin{cases}
2x-3y+z  &=-1 \\
x-y +2z&=-3\\
3x+y -z&=9\\
\end{cases}


Remarque : Avec l’aide de la méthode sp.Matrix().rref() , nous pouvons mettre une matrice sous forme d’échelon de ligne réduit . Matrix().rref() renvoie un tuple de deux éléments. La première est la forme d’échelon de ligne réduite et la seconde est un tuple d’indices des colonnes pivot.

# Des exercices d'algèbre 2

## Exercice A
Soit $E$ l'espace vectoriel $\mathbb{R}^3$ . On considère l'application linéaire $f$ de $E$ dans $E$ dont la matrice dans la base canonique ${\cal E}$ de $E$ est
$$ A = \left(\begin{array}{rrr}
            1 &0& 2\\
            0& 1 &0\\
            2&0 & 1
           \end{array}\right).
$$
1. Soit $v$ le vecteur de $E$ de coordonnées $(x, y, z)$ dans la base ${\cal E}$ . Calculer $f (v)$.
2. Calculer le rang de $A$. L'endomorphisme $f$ est-il injectif, surjectif, bijectif?
3.  On pose $v_1 = (0, 1, 0)$ , $v_2 = (1, 0,- 1)$ et $v_3 = (1, 0, 1)$. Montrer que ${\cal V} = (v_1 , v_2 , v_3 )$ est une
base de $E$.
4.  Calculer $f (v_1 )$ , $f (v_2 )$ et $f (v_3 )$ en fonction des éléments de ${\cal V}$.
5.  Déterminer la matrice $B$ de $f$ dans la base ${\cal V}$.
6.  Ecrire la matrice de passage $P$ de la base ${\cal E}$ \`a  la base ${\cal V}$.
7. Calculer $P^{-1}$.
8.  Donner la relation qui lie les matrices $A$, $B$, $P$ et $P^{-1}$ . Comment peut -on calculer $A^n$? 

## Exercice B
On considère la matrice $A$ suivante, où $m$ désigne un nombre réel : 
$$A=\left(\begin{array}{ccc}
m & (1+m^2) & 2m \\\\
(2-m^2) & m & 1 \\\\
4 & 2m & 4 
\end{array}
\right).$$ 

1. Montrer que le déterminant de la matrice $A$ est égal à  $2m^2-4$. 
Pour quelles valeurs du réel $m$, la matrice $A$ est-elle inversible?
2. On se place dans le cas où $A$ est inversible. Déterminer la comatrice de $A$ puis la matrice inverse de $A$.
3. Soit $f$ l'endomorphisme de $R^3$ dont la matrice associée dans la base canonique de $R^3$ est $A$. Pour quelles valeurs de $m$, l'application $f$ est un isomorphisme de $R^3$ dans $R^3$ ? 

## Exercice C

Pour $m\in \mathbb{R}$, on note $A_m = \begin{pmatrix}
3 & 1 & -2 \\ 2+m & 2 & -2 \\ 4 & 2+m & -3 \end{pmatrix}$ et $f_m : \mathbb{R}^3 \to \mathbb{R}^3$ l'endomorphisme de $\mathbb{R}^3$ ayant pour matrice $A_m$ dans la base canonique de $\mathbb{R}^3$.

1. Calculer $\det(A_{m})$.  
 Pour quelles valeurs de $m$ a-t-on $f_m$ bijectif ? Injectif ?

2. Calculer $\ker(f_m)$ en distinguant suivant les valeurs de $m$.
3. Dans cette question, on s'intéresse à    $A_1$ et $f_1$  (c'est-à-dire qu'on fixe $m=1$ dans la matrice $A_{m}$).

a. Calculer $A_1^{-1}$.

b. En déduire, pour $(x,y,z)\in \mathbb{R}^3$, une expression de $f_1^{-1}(x,y,z)$.


4. On fixe maintenant $m=0$ et on note $f=f_0$.

a. Donner une base de $\text{Im}(f)$.

b. Montrer que $f$ est la projection sur un sous-espace vectoriel $F$  parallèlement à    un sous-espace vectoriel $G$ (à préciser).

c. Donner une base $\mathcal{B}$ de $\mathbb{R}^3$ dans laquelle la matrice de $f$ est $D = \begin{pmatrix} 0 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{pmatrix}.$



## A l'aide de numpy et sympy,  obtenez un maximum de resultats avec Python !